### ISSUE TITLE
ReceiveWithLatestOffset receiver read old messages

### ISSUE THREAD

**Issue by LukaszBrygala** [Azure/azure-event-hubs-go#118]
I am using library to read events from IotHub.

### Expected Behavior

I would like the receiver configured with ReceiveWithLatestOffset to read events starting from the latest.

### Actual Behavior

Receiver is reading old messages.

### Environment
- Go version: go1.12.5 darwin/amd64
- Version of Library: github.com/Azure/azure-event-hubs-go v1.3.0

**Comment by LukaszBrygala** [comment]
After some testing I've discovered, that the behavior depends on the ordering of options passed to the Receive function.

When I pass following options:
```
	opts := []eventhub.ReceiveOption{
                	eventhub.ReceiveWithLatestOffset(),
		eventhub.ReceiveWithConsumerGroup(consumerGroup),
	}
```
receiver is reading old messages despite ReceiveWithLatestOffset. But when I switch options ordering like this:
```
	opts := []eventhub.ReceiveOption{
		eventhub.ReceiveWithConsumerGroup(consumerGroup),
                	eventhub.ReceiveWithLatestOffset(),
	}
```
receiver is working as expected.

**Comment by LukaszBrygala** [comment]
OK, now I understand. ReceiveWithLatestOffset is internally doing this:
```
r.offsetPersister().Write(r.namespaceName(), r.hubName(), r.consumerGroup, r.partitionID, checkpoint)
```
and that line depends on consumerGroup, which is set to default until ReceiveWithConsumerGroup is processed.

I think it would be good to improve this or describe in documentation, that options must be passed in proper order.

**Comment by devigned** [comment]
Sorry... just getting back from vacation.

Options should not need to be in any particular order. This is a bug and an evil one at that.

Thank you for the heads up!

**Comment by R290** [comment]
Before fixing #95, I've decided to look into this bug since it seems somewhat related. The problem arises in: https://github.com/Azure/azure-event-hubs-go/blob/64aa20d6c1260df9c7fc558e6892adc9bec9ff9f/receiver.go#L131 Where options are handles by order of entry by the user:
```golang
for _, opt := range opts {
	if err := opt(receiver); err != nil {
		return nil, err
	}
}
```
My first idea was to get the function name from `opt` (say `ReceiveWithConsumerGroup`) but I've not yet found a way to do this in Go. The alternative would be to add some priority or other attribute to `ReceiveOption`?

**Comment by devigned** [comment]
Rather than trying to use reflection or to place a priority on options, @R290 what do you think about removing the direct call within the options to `receiver.storeLastReceivedCheckpoint(..)` and replacing it with a body that sets a field on the receiver struct, and then after the options for loop, the call to `storeLastReceivedCheckpoint` would occur. This would allow for options to be specified in any order, configure the receiver, and only after configuration is complete, act on the fully configured receiver. Thoughts?

https://github.com/Azure/azure-event-hubs-go/blob/64aa20d6c1260df9c7fc558e6892adc9bec9ff9f/receiver.go#L84-L103

**Comment by R290** [comment]
Your solution is definitely the more elegant one. I created and tested a proof of principle in: https://github.com/R290/azure-event-hubs-go/commit/7765834f2d72e2b0595045db200b55431bdee4c4 I guess the error return of the `ReceiveOption` type could be removed since this is no longer used anywhere?

I also added a check before `receiver.storeLastReceivedCheckpoint(..)` which should solve issue #95 (the FilePersister being overwritten).

**Comment by devigned** [comment]
You're right. The error return could be omitted, but I would prefer to leave it since I could easily see adding new configuration options in the future which will have some error return possible (I really don't like this argument b/c yagni, but I've run into needing the error for other options and adding it after the fact is pretty ugly).

**Comment by R290** [comment]
Then we leave the error as is. Before submitting a PR, there is a small issue with my imports. Upon saving `receiver.go` VS Code automatically changes the imports to:
```go
import (
	"context"
	"fmt"
	"time"

	common "github.com/Azure/azure-amqp-common-go/v2"
	"github.com/devigned/tab"
	"pack.ag/amqp"

	"github.com/Azure/azure-event-hubs-go/v2/persist"
)
```
The original is:
```go
import (
	"context"
	"fmt"
	"time"

	"github.com/Azure/azure-amqp-common-go/v2"
	"github.com/devigned/tab"
	"pack.ag/amqp"

	"github.com/Azure/azure-event-hubs-go/v2/persist"
)
```
Which variant should I use in the PR, with or without the added `common`?
I'm using `go version go1.12.7 linux/amd64` with modules enabled and `go.mod` is unchanged.

**Comment by devigned** [comment]
You can leave it with the added `common`. It will remove the ambiguity of `common` uses in that code file.
