### ISSUE TITLE
The right way to new a event

### ISSUE THREAD

**Issue by metrue** [Azure/azure-event-hubs-go#124]
Apologize first, this is a question more than an issue, document is not clear on this also, https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.eventdata.-ctor?view=azure-dotnet

There are two ways to create an in current code base, 
```Go
// NewEventFromString builds an Event from a string message
func NewEventFromString(message string) *Event {
	return NewEvent([]byte(message))
}

// NewEvent builds an Event from a slice of data
func NewEvent(data []byte) *Event {
	return &Event{
		Data: data,
	}
```
Basically what they do is put payload []byte to an `Event`'s `Data` field.

My question is what exactly the `Data` of an event means, here is a scenario, I'd like to send an `ServiceStopped` event to Azure EventHub, I have to ways to do it, which one is correct?

```Go
event := NewEvent([]byte("ServiceStopped")
event.Set("host_name", "xxx")
event.Set("service_name": "yyy")

hub.Send(event)
```

or 
```Go
evt := map[string]string{
    "service_name": "xxx",
    "host_name": "xxx",
};
data, _  := json.Marshal(evt)

event := NewEvent(data)
hub.Send(event)
```
and how the difference of above two ways gonna impact the event consumers (for example the consumer is Splunk)

### Environment
- OS: Darwin MinghedeMacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
- Go version: go version go1.12.5 darwin/amd64
- Version of Library: v2

**Comment by gavinfish** [comment]
In my opinion, `Data` represents the event type in your system. When you consume a specific event, you may need more details which you can put them in the `properties`.

I think you should use the first one. Below code shows how to deal with `Data` and `properties` when converting an event to an amqp message.
https://github.com/Azure/azure-event-hubs-go/blob/a3c7e1b4bd28f5aff938933975e8045396da373f/event.go#L127-L142

**Comment by metrue** [comment]
Thanks @gavinfish for quick response, then I am a little curious about why use `New(name string)` or `New(type string)` to create an event,  just a quick look at `amqp`'s spec,  it seems like  `Data` can carry something, not just the "event name" or "event type"

http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-complete-v1.0.pdf
```
<type name="data" class="restricted" source="binary" provides="section">
<descriptor name="amqp:data:binary" code="0x00000000:0x00000075"/>
</type>
A data section contains opaque binary data
```

**Comment by gavinfish** [comment]
I am not sure what's your concern about the `New(name string)` method. Do you mean you want to save more than just message in the `Data`? Indeed you put anything in it and just write proper handler to deal with it. But I think it is more nature to have a `properties` to save extra information here. You do not have to serialize/unserialize your data like the second sample you provide.

**Comment by devigned** [comment]
To give just a bit of background here. Event construction was specifically intended to be abstract from the domain model of the application. Since `Data` is just a bunch of bits, you can use it to do whatever you want with it. You could marshal JSON to a string, marshal a protobuf to binary, or anything else you want. We didn't want to be too prescriptive about how people were putting their bits on the wire.

The use of properties is completely optional and adds to the overall size of the message. In Event Hubs, I don't see much value in using the Properties over an Event.Data block. Though, in Service Bus, it becomes more interesting since you can build queries and routing based on Properties (see: https://github.com/Azure/azure-service-bus-go/blob/master/priority_subscription_example_test.go where we use properties to create priorities for messages and query them with a SQLQuery).

Also, AMQP 1.0 describes how you can use an AMQP value section to describe a payload as an AMQP value: http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-amqp-value. Right now, we don't expose this, but if someone requested it in the future, we'd put more design thought into supporting it.

**Comment by metrue** [comment]
@gavinfish 

What I concern is how these two different ways impact the downstream consumers, for example, we are going to enable `Capture` feature, then Splunk will consume those events, so if Splunk does not care the `Properties`, then I should put all the data into `Data` block.

@devigned Thank you so much for your clear explanation, according to your explanation, the best ways maybe like,

```Go
evt := map[string]string{
    "service_name": "xxx",
    "host_name": "xxx",
};
data, _  := json.Marshal(evt)
event := NewEvent(data)
event.Set("content_type", "application/json")
hub.Send(event)
```
