### ISSUE TITLE
amqp:link:stolen every time I connect to event hub

### ISSUE THREAD

**Issue by koalalorenzo** [Azure/azure-event-hubs-go#181]
### Expected Behavior
It should be able to start and stop on the fly. I have implemented when stopped, a graceful stop that closes the connection in case that was the issue. (it runs `eventhub.Hub.Close`)

### Actual Behavior
Every time I start a new hub by invoking `eventhub.NewHubFromConnectionString` I get the following error:
```
*Error{Condition: amqp:link:stolen, Description: At least one receiver for the endpoint is created with epoch of '1838', and so non-epoch receiver is not allowed. Either reconnect with a higher epoch, or make sure all epoch receivers are closed or disconnected. TrackingId:835f1f83-8004-46a2-b0dc-8b4e0868485d_B25, SystemTracker:evh-~REDACTED~:eventhub:log-eventhub~16383, Timestamp:2020-07-06T08:28:14 Reference:04ba6f2b-627f-4fb7-83e3-be20b3e1c59d, TrackingId:c52b762b-cf66-4590-931d-4e514bbc6d34_B25, SystemTracker:evh-~REDACTED~:eventhub:log-eventhub~16383|$default, Timestamp:2020-07-06T08:28:14 TrackingId:b584893ba7e94d6cbfa41ab212c0db39_G24, SystemTracker:gateway5, Timestamp:2020-07-06T08:28:14, Info: map[]}
```

I tried creating a new ConnectionString, or a new Shared access policy but the issue persists. 

### Environment
- OS: macOS 10.15.5 but also in a Docker Containers (`golang:1.14`)
- Go version: 1.14.4
- Version of Library: v3

**Comment by rgbusato** [comment]
same 😞

**Comment by catalinaperalta** [comment]
Hi! Thanks for reaching out and sorry for the delay in getting to this. It seems this could come about for a few different reasons. One could be that the event hub has an epoch set and therefore cannot be used with non-epoch receivers, it should instead be used with a receiver with a higher epoch. The other problem could be that there are several receivers trying to attach to a consumer group, the epoch feature is so that only one receiver is attached to the consumer group at a time. At any rate, I'd be interested in knowing what case caused this for you?

**Comment by devigned** [comment]
This might be helpful:
https://github.com/Azure/azure-event-hubs-go/blob/2fcae0bd6b53327605d662cbde3a4dd1375b40b3/receiver.go#L117-L132

**Comment by devigned** [comment]
Also, the EventProcessorHost is resilient to these kinds of error and will load balance consumers to maximize throughput. See https://github.com/Azure/azure-event-hubs-go#event-processor-host.

**Comment by koalalorenzo** [comment]
This thing is so old that I am no longer using Azure, Closing
