### ISSUE TITLE
Fails to install with "not enough arguments in call"

### ISSUE THREAD

**Issue by tomklino** [Azure/azure-event-hubs-go#201]
### Expected Behavior
go get -u github.com/Azure/azure-event-hubs-go/...

successful installation 

### Actual Behavior
```bash
$ go get -u github.com/Azure/azure-event-hubs-go/...
go: finding golang.org/x/crypto latest
go: finding golang.org/x/net latest
go: finding golang.org/x/sys latest
go: finding gopkg.in/yaml.v3 latest
go: finding github.com/golang/groupcache latest
# github.com/Azure/azure-event-hubs-go/storage
../../go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/storage/storage.go:568:42: not enough arguments in call to blobURL.ToBlockBlobURL().Upload
        have (context.Context, *bytes.Reader, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions)
        want (context.Context, io.ReadSeeker, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions, azblob.AccessTierType, azblob.BlobTagsMap)
../../go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/storage/storage.go:592:45: not enough arguments in call to blobURL.ToBlockBlobURL().Upload
        have (context.Context, *bytes.Reader, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions)
        want (context.Context, io.ReadSeeker, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions, azblob.AccessTierType, azblob.BlobTagsMap)

```
### Environment
- OS: Windows (WSL2 Ubuntu 20)
- Go version: go version go1.13.8 linux/amd64
- Version of Library: Any

I've been following the guide here: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-go-get-started-send to the letter  - got to here: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-go-get-started-send#go-packages

running exactly what's typed in the official guide delivered the message - what's wrong here? Can't find anyone else encountering this error

**Comment by devigned** [comment]
The key indication here is that `latest` of each dependency is being pulled down, rather than the version of the dependency required in the `go.mod` and `go.sum` files for `github.com/Azure/azure-event-hubs-go`.

Seems like you might be running this in your `GOPATH` with `GO111MODULE=auto` ([the default](https://golang.org/cmd/go/#hdr-Module_support)). You have 2 options.
1. You can run `go get -u github.com/Azure/azure-event-hubs-go/...` outside of your `GOPATH`, which will cause it to use Go modules by default, rather than fetching latest for each module.
2. You can run `GO111MODULE=on github.com/Azure/azure-event-hubs-go/...`.

This is great feedback and the docs should be updated to help folks from running into this problem.

Learning about how Go fetches dependencies and how Go modules work is super helpful. Happy to answer questions you may have about modules vs fetching latest and stuff like that.

Hope this helps.

**Comment by tomklino** [comment]
Thank you for the quick reply

I should have mentioned it in my question, but I actually have `GO111MODULE=on` and I'm running it from `~/workspace/go-playground/event-hubs` (so not the `GOPATH`), and I encounter the issue nonetheless.

Any ideas what else can I do?

(I might be missing something in my understanding of how go modules work)

**Comment by tomklino** [comment]
I've deleted my ~/go contents and ran `go mod init <something>` in my code directory - got a different result this time, but ends with the same error:

```
...
go: finding github.com/google/uuid v1.1.2
go: finding go.opencensus.io v0.22.5
go: finding github.com/Azure/go-autorest v14.2.0+incompatible
go: finding github.com/Azure/azure-sdk-for-go v49.0.0+incompatible
go: finding golang.org/x/sys latest
go: finding github.com/Azure/go-autorest/tracing v0.6.0
go: finding github.com/mitchellh/mapstructure v1.4.0
go: finding github.com/mattn/go-ieproxy v0.0.1
go: finding github.com/Azure/go-autorest/autorest v0.11.12
go: finding github.com/Azure/go-autorest/autorest/date v0.3.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding golang.org/x/crypto latest
go: finding golang.org/x/net latest
go: finding gopkg.in/yaml.v3 latest
go: finding github.com/jpillora/backoff v1.0.0
go: finding github.com/Azure/go-autorest/autorest/adal v0.9.5
go: finding github.com/sirupsen/logrus v1.7.0
go: finding github.com/Azure/go-autorest/autorest/validation v0.3.0
go: finding github.com/mitchellh/go-homedir v1.1.0
go: finding github.com/pmezard/go-difflib v1.0.0
# github.com/Azure/azure-event-hubs-go/storage
../../../go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/storage/storage.go:568:42: not enough arguments in call to blobURL.ToBlockBlobURL().Upload
        have (context.Context, *bytes.Reader, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions)
        want (context.Context, io.ReadSeeker, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions, azblob.AccessTierType, azblob.BlobTagsMap)
../../../go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.3.1/storage/storage.go:592:45: not enough arguments in call to blobURL.ToBlockBlobURL().Upload
        have (context.Context, *bytes.Reader, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions)
        want (context.Context, io.ReadSeeker, azblob.BlobHTTPHeaders, azblob.Metadata, azblob.BlobAccessConditions, azblob.AccessTierType, azblob.BlobTagsMap)
```

**Comment by devigned** [comment]
Ok... Here's what's going on and why the documentation should be changed (@catalinaperalta & @jhendrixMSFT).

When you run `go get -u` Go is going to try to update the dependencies with the latest version it can based on the module dependencies. In this case, that means `go: github.com/Azure/azure-storage-blob-go upgrade => v0.11.0` from `github.com/Azure/azure-storage-blob-go v0.6.0` specified [here](https://github.com/Azure/azure-event-hubs-go/blob/c5588f4995ffd7ed3e85d92d6b4a2b1e6ee1b5ac/go.mod#L9). The problem with this is that the storage library made a breaking change between `v0.6.0` and `v0.11.0`, which is why you see the `not enough arguments` error.

I bet if you run the following, you'll be all set.
```shell
mkdir ehtest
cd ehtest
go clean --modcache # probably not needed, but just to be safe
go mod init github.com/foo
go get github.com/Azure/azure-event-hubs-go/...
```

**Comment by tomklino** [comment]
Yes. Looks like that did the trick. Thank you!
