### ISSUE TITLE
Is there a way to enable some debug logging while sending event batches?

### ISSUE THREAD

**Issue by favoretti** [Azure/azure-event-hubs-go#246]
When using `eventhub.SendBatch` method with an `EventBatchIterator` - is there a way to enable some sort of debug logging to let it report batch sizes it's sending, total messages sent and so on?

Thanks!

**Comment by richardpark-msft** [comment]
There isn't anything like this currently. 

You can wrap the normal EventBatchIterator since it's really the interface that's used for the `SendBatch()` function and just log tracing or diagnostics.

```go
	BatchIterator interface {
		Done() bool
		Next(messageID string, opts *BatchOptions) (*EventBatch, error)
	}
```

So implementing a wrapper function with two functions and then pass your wrapper, rather than EventBatchIterator, into SendBatch().

Closing but please reopen  if you have further questions.
