### ISSUE TITLE
High Throughput Single Partition Verification

### ISSUE THREAD

**Issue by devigned** [Azure/azure-event-hubs-go#51]
Saturate sends on a 100 throughput unit Event Hub instance for a single partition.

**Comment by connor4312** [comment]
I ran some tests locally on a service we're building. Generally things seemed to work well. [Here's a pdf](https://memes.peet.io/img/12c2cc14-2a43-4f97-8e35-342457931784.pdf) of some prometheus charts. CPU of the consuming application, which did a little more than just receiving events, sat around 6-8% of one of the cores on my MacBook.

**Comment by devigned** [comment]
@connor4312 thank you for sharing your results!! It'd be great to see a collection of these from many sources.

It looks like you are getting throttled, so I'd imagine it's due to EH slowing you down.

How many throughput units are you running? 
How large are the messages?
Is this for a single partition?
Are you running anything else on the Event Hub namespace? Event Hubs are throttled at the namespace level (namespace has many hubs). If you have a hub running on the same namespace, you will run into competing throughput.
Are you seeing 1000 messages / 30s?

I was focusing on sends rather than receives in this issue. I'll open another issue evaluate receive throughput.

**Comment by connor4312** [comment]
For this test, I was intentionally sending all data through a single partition. The graphs are given in rates per second, so that is 1000 events per second, averaged over that `[30s]` vector that you saw. So this may be how event hub throttling surfaces, I've not tried to hit the limits with event hubs before this test 🙂 The messages were 14 byte protobuf messages. 

Overall the client seems to hold up quite well. I was both publishing and receiving using this package. Happy to share the code via email (the service is not open source yet) if you want to see it, but it's fairly straightforward.

**Comment by devigned** [comment]
Initial tests running against the 100 throughput unit instance targeting a single partition is providing sustained sends of 1.3 - 2.15 million messages / minute. I'm going to continue to run this test over an extended period to verify robustness.
