### ISSUE TITLE
Add web sockets support

### ISSUE THREAD

**Issue by devigned** [Azure/azure-event-hubs-go#66]
### Expected Behavior
Should be able to connect to Event Hubs via web sockets rather than over the standard AMQP ports to better support common open ports.

### Actual Behavior
The library only supports common AMQP ports.

/cc #65

**Comment by vcabbage** [comment]
FWIW, I've experimentally used `pack.ag/amqp` and `golang.org/x/net/websocket` to do this. I've done essentially no validation of how well it works or whether it fully conforms to the spec, just sent and received a few messages.

```go
host := "<name>.servicebus.windows.net"

conn, err := websocket.Dial("wss://"+host+"/$servicebus/websocket", "amqp", "http://localhost/")
if err != nil {
	log.Fatal(err)
}
conn.PayloadType = websocket.BinaryFrame

client, err := amqp.New(conn,
	amqp.ConnSASLPlain(key, secret),
	amqp.ConnServerHostname(host),
)
```

**Comment by vcabbage** [comment]
I'm hesitant to add non-stdlib deps to `pack.ag/amqp`.

In the case of websockets it also forces a decision of whether to use `golang.org/x/net/websocket` or the more popular `github.com/gorilla/websocket`. I used the former for my experiment because it directly implements `net.Conn`, unlike the gorilla implementation, but that doesn't necessarily mean it's the better choice.

One option would to be to add a transport registration function to `pack.ag/amqp` like:
```go
amqp.RegisterTransport(scheme string, dialFunc func(addr string) (net.Conn, error))
```
Then we could have a sub-package of `pack.ag/amqp` that had an implementation. For the sake of example, say `pack.ag/amqp/websocket` and calling `websocket.Register()` would register "ws" and "wss". The downside of this is that it's a little extra work for the user and the registrations would be package scoped. This is a rough idea so far and I think it could use some refinement.

The same mechanism might be useful for vendor specific schemes, particularly if the `dialFunc` could also return `amqp.ConnOption`s. Though I suppose most vendors would develop a library like this one that uses `pack.ag/amqp` internally.

**Comment by devigned** [comment]
I was also concerned about adding a dependency to `pack.ag/amqp`. It's so nice to only have a dependency on the standard lib.

I can get behind that solution. Consumers of EH or SB libs would not be impacted by the change. EH and SB libs could call `websocket.Register` in init or something.

I'm worried about taking a dependency on either package after reading through https://github.com/golang/go/issues/18152. Do you have a preference, @vcabbage?

**Comment by vcabbage** [comment]
It seems like the biggest issue with `x/net/websocket` is the API, which is awkward for typical usage but may be ideal for AMQP since it's just using it as a transport.

Reading through the spec, I think the example implementation I posted is more or less correct. As far as I can see the only thing missing is AMQP connection/link-level redirect handling. Unless there's an obvious way to handle redirects it may make sense to defer on that for the time being.

**Comment by devigned** [comment]
Totally agree about `x/net/websocket`. The convenience of getting a `net.Conn` is quite tempting.

I know link redirects are used in Azure IoT to redirect to a link to the underlying Event Hub. I haven't created an issue yet, but it's something that I was going to take a look at end of week. I know the error is modeled in vcabbage/amqp, but I don't think it's really used. Should this be something baked into amqp lib, or higher level?

**Comment by devigned** [comment]
For connection redirects, are referring to HTTP redirects?

**Comment by vcabbage** [comment]
I was referring to the AMQP connection redirects: http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-connection-error

HTTP redirects are likely the easiest thing to handle.
